baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '公会那点事'
theme = 'anatole'
[params]
  author = 'Four Seas'
  copyright = 'Four Seas'
  profilePicture = 'https://assets.fourfire.wang/resource/logo.png'
